name: Test

on:
  # Trigger at every push. Action will also be visible from Pull Requests to master
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Test
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java_version: [11, 17, 19]
    runs-on: ${{ matrix.os }}

    steps:
    # Git Checkout
    - name: Checkout Code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::712023778557:role/github/GitHub-Testing-NF-Quilt
        aws-region: us-east-1

    - name: Setup Java ${{matrix.java_version}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java_version}}
        distribution: 'temurin'
        architecture: x64
        cache: gradle
       
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run Gradle Tests
      run: make test
      env:
        LOG4J_DEBUG: true

    - name: Archive production artifacts (Windows only)
      uses: actions/upload-artifact@v4
      if: ${{ always() && matrix.os  == 'windows-latest' }}
      with:
        name: nf-quilt-test-reports-${{ matrix.os }}-${{ matrix.java_version }}
        path: |
            /D:/a/nf-quilt/nf-quilt/plugins/nf-quilt/build/reports/tests/test/index.html
        overwrite: true
    - name: Archive production artifacts (Linux and MacOS)
      uses: actions/upload-artifact@v4
      if: ${{ always() && matrix.os != 'windows-latest' }} 
      with:
        name: nf-quilt-test-reports-${{ matrix.os }}-${{ matrix.java_version }}
        path: |
            ${{ github.workspace }}/nf-quilt/plugins/nf-quilt/build/reports/tests/test/
        overwrite: true

