name: Test

on:
  # Trigger at every push. Action will also be visible from Pull Requests to master
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    # Git Checkout
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Install Quilt3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python -m pip install quilt3
    - run: which quilt3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
           
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Gradle Tests
      run: make test

    - name: Archive production artifacts
      if: ${{ success() }} || ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: nf-quilt-test-reports
        path: |
          /home/runner/work/nf-quilt/nf-quilt/plugins/nf-quilt/build/reports/tests/test/
